### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Rituchan** [silviomec/Progettazione-del-sw#1]
- [x] Modificare il layout di UpdateStruttura per chiarire che va innanzitutto scelta la partita IVA (anche nel caso dell'aggiunta di una nuova struttura);
- [x] Settare colore cella canone verde o rossa a seconda della scadenza.

**Comment by Korenji** [comment]
- [x] Rivedere lista delle inserzioni in modo da evidenziare quelle con il canone non saldato.
